services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: ai-challenge-frontend
    ports:
      - "3000:3000"
    environment:
      - REACT_APP_API_URL=/api  # Nginx가 /api로 프록시하므로 상대 경로 사용
    volumes:
      - npm-cache:/root/.npm # npm 캐시 볼륨 마운트
      - ./frontend:/app # 프론트엔드 소스 코드 변경 시 실시간 반영을 위한 마운트 (선택 사항)
    networks:
      - frontend-network

volumes:
  npm-cache: # npm 캐시를 위한 볼륨 정의

networks:
  frontend-network:
    driver: bridge

version: '3.8'

