spring:
  application:
    name: AI-Challenge
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
        show_sql: true
    open-in-view: false

document:
  upload:
    path: /app/document-upload

openai:
  api:
    key: ${OPENAI_API_KEY}
